project:
  type: website
  output-dir: docs

website:
  title: "Data Science"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - icon: slack
        href: "https://sps502f22.slack.com"
        aria-label: Slack
      - icon: cloud-fill
        href: "https://rstudio.cloud"
        aria-label: RStudio.cloud


format:
  html:
   template-partials:
    - html/home/title-block.html
   theme:
    light: flatly
    dark: darkly



