project:
  type: website
  output-dir: docs

website:
  title: "Data Science"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai



